
services:

  # nordvpn:
  #   build:
  #     context: ./nordvpn
  #     dockerfile: Dockerfile
  #   container_name: honeypot_nordvpn
  #   hostname: honeypot-vpn
  #   cap_add:
  #     - NET_ADMIN
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0
  #   environment:
  #     NORDVPN_TOKEN: ${NORDVPN_TOKEN}
  #     NORDVPN_COUNTRY: ${NORDVPN_COUNTRY:-Argentina}
  #   volumes:
  #     - ./nordvpn/entrypoint.sh:/entrypoint.sh:ro
  #   entrypoint: ["/bin/bash", "/entrypoint.sh"]
  #   networks:
  #     - recon_net
  #   healthcheck:
  #     test: ["CMD-SHELL","nordvpn status | grep -q 'Status: Connected'" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 12
  #     start_period: 30s
  #   restart: unless-stopped

  recon:
    build:
      context: ./recon
      args:
        USER_ID: ${HOST_UID:-1000}
        GROUP_ID: ${HOST_GID:-1000}
    container_name: honeypot_recon
    environment:
      TARGET_DOMAIN: ${TARGET_DOMAIN:?Define TARGET_DOMAIN in .env}
      MAX_DEPTH: ${MAX_DEPTH:-4}
      RECON_OUTPUT: /work/recon/active-sites.txt
      SITES_DIR: /work/sites
      GENERATED_OUTPUT: /work/generated
    #network_mode: "service:nordvpn"  
    networks:
      recon_net:
        ipv4_address: 172.50.0.20
    #depends_on:
    #  nordvpn:
    #    condition: service_healthy
    volumes:
      - ./sites:/work/sites:rw
      - ./generated:/work/generated:rw
      - ./recon-output:/work/recon:rw
    restart: "no"

  sites:
    image: nginx:alpine
    container_name: honeypot_sites
    depends_on:
      recon:
        condition: service_completed_successfully
    expose:
      - "8080"
    volumes:
      - ./sites:/usr/share/nginx/sites:ro
      - ./generated:/etc/nginx/generated:ro
      - nginx_logs:/var/log/nginx
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/generated/nginx.conf"]
    networks:
      sites:
        ipv4_address: 172.40.0.20
    healthcheck:
      test:
        [ "CMD-SHELL","nginx -t && wget -qO- http://127.0.0.1:8080/__health >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: honeypot_nginx
    depends_on:
      recon:
        condition: service_completed_successfully
      sites:
        condition: service_healthy
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./generated/proxy.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
    networks:
      zeeknet:
        ipv4_address: 172.20.0.10
      sites:
        ipv4_address: 172.40.0.10
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && wget -qO- http://127.0.0.1/__health >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  zeek:
    image: blacktop/zeek
    container_name: zeek_monitor
    command: ["-i", "enX0","LogAscii::use_json=T"]
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./pcap:/pcap:rw
      #- ./ignore_local_src.zeek:/usr/local/zeek/share/zeek/site/ignore_local_src.zeek:ro
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    networks:
      elknet:
        ipv4_address: 172.30.0.10

    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

    restart: unless-stopped

  elasticsearch-init:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy

    networks:
      elknet:

    volumes:
      - ./elasticsearch/templates:/templates:ro
      - ./elasticsearch/init.sh:/init.sh:ro

    entrypoint: ["/bin/sh", "/init.sh"]


  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      elknet:
        ipv4_address: 172.30.0.11
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      elknet:
        ipv4_address: 172.30.0.12
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:5601/api/status > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    
    restart: unless-stopped

  kibana-init:
    image: curlimages/curl:latest

    depends_on:
      kibana:
        condition: service_healthy
    
    networks:
      elknet:

    volumes:
      - ./kibana/init.sh:/init.sh:ro
      - ./kibana/honeypot_dashboard.ndjson:/dashboard.ndjson:ro

    entrypoint: ["/bin/sh", "/init.sh"]

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.10
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./pcap:/logs:ro
      - ./data:/data:ro
      - nginx_logs:/var/log/nginx:ro
      - ./sites/sites_events.jsonl:/sites/sites_events.jsonl:ro
    depends_on:
      - logstash
    networks:
      - elknet
    restart: unless-stopped

  zeek_predictor:
    build: 
      context: ./predictor
    container_name: zeek_predictor
    restart: unless-stopped
    volumes:
      - ./pcap:/app/logs:ro
      - ./predictor/predict/model:/app/model:ro
      - ./data:/data:rw
    networks:
      - zeeknet
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  nginx_logs:

  
networks:
  zeeknet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  elknet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  sites:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.40.0.0/24
  recon_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
