input {
  beats {
    port => 5044
  }
}

filter {

  if [log_type] == "detections" {

    mutate {
      add_field => {
        "[@metadata][target_index]" => "honeypot-detections"
      }
    }

  } else if [log_type] == "zeek" {

    json {
      source => "message"
    }

    mutate {
      rename => {
        "[id.orig_h]"       => "[source][ip]"
        "[id.orig_p]"       => "[source][port]"
        "[id.resp_h]"       => "[destination][ip]"
        "[id.resp_p]"       => "[destination][port]"
        "[orig_pkts]"       => "[source][packets]"
        "[resp_pkts]"       => "[destination][packets]"
        "[orig_ip_bytes]"   => "[source][bytes]"
        "[resp_ip_bytes]"   => "[destination][bytes]"
        "[proto]"           => "[network][transport]"
      }

      add_field => {
        "[@metadata][target_index]" => "honeypot-network"
      }
    }

    date {
      match => [ "ts", "UNIX" ]
      target => "@timestamp"
    }
    
  } else if [log_type] == "nginx" {

    mutate {
      add_field => {
        "[@metadata][target_index]" => "honeypot-nginx"
      }
    }

  } else if [log_type] == "sites" {

    mutate {
      add_field => {
        "[@metadata][target_index]" => "honeypot-sites"
      }
    }

  } else {

    mutate {
      add_field => {
        "[@metadata][target_index]" => "honeypot-unknown"
      }
    }
  }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]

    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
  }

}